version: "3.8"

services:
  apromore:
    build: .
    ports:
      - "9000:9000"

  db:
    image: mysql:5
    volumes:
      - ./Supplements/database/db-mysql.sql:/docker-entrypoint-initdb.d/apromore.sql
    ports:
      - "3306:3306"

  impala:
    ports:
      - "21050:21050"

volumes:
  preprocess-data:
