version: "3.8"

services:
  apromore:
    build: .
    environment:
      JAVA_OPTS: "-server -Xmx8g -Xmn1g"
    ports:
      - "9000:9000"
    depends_on:
      - db
      - impala

  db:
    image: mysql:5
    command: --max_allowed_packet=2G
    environment:
      MYSQL_DATABASE: apromore
      MYSQL_ROOT_PASSWORD: MAcri
      MYSQL_USER: apromore
      MYSQL_PASSWORD: MAcri
    volumes:
      - ./Supplements/database/db-mysql.sql:/docker-entrypoint-initdb.d/apromore.sql
    expose:
      - "3306"

  impala:
    image: apache/kudu:impala-latest
    volumes:
      - preprocess-data:/tmp/preprocess_data
    command: impala

volumes:
  preprocess-data:
